from pytmx.util_pygame import load_pygame
tmx_data = load_pygame("maps/map B300 x4.tmx")
tmx_data_b = load_pygame("maps/map B200-A200 x4.tmx")
tmx_data_c = load_pygame("maps/map CDI.tmx")
tmx_data_d = load_pygame("maps/map A100.tmx")
tmx_data_e = load_pygame("maps/B100.tmx")
layers_3 =  {
    "sol3": tmx_data.layers[0],
    "COULOIR_A": tmx_data.layers[1],
    "COULOIR_B": tmx_data.layers[2],
    "COULOIR_N": tmx_data.layers[3],
    "COULOIR_C": tmx_data.layers[4],
    "COULOIR_D": tmx_data.layers[5],
    "COULOIR_E": tmx_data.layers[6],
    "ESCALIER_1": tmx_data.layers[7],
    "ESCALIER_2": tmx_data.layers[8],
    "ESCALIER_3": tmx_data.layers[9],
    "ESCALIER_4": tmx_data.layers[10],
    "ESCALIER_8": tmx_data.layers[11],
    "murs3": tmx_data.layers[12],
    "A301": tmx_data.layers[13],
    "A302": tmx_data.layers[14],
    "A303": tmx_data.layers[15],
    "A304": tmx_data.layers[16],
    "A305": tmx_data.layers[17],
    "A306": tmx_data.layers[18],
    "A307": tmx_data.layers[19],
    "A308": tmx_data.layers[20],
    "A309": tmx_data.layers[21],
    "A310": tmx_data.layers[22],
    "B311": tmx_data.layers[23],
    "B312": tmx_data.layers[24],
    "B313": tmx_data.layers[25],
    "B314": tmx_data.layers[26],
    "B315": tmx_data.layers[27],
    "B316": tmx_data.layers[28],
    "B317": tmx_data.layers[29],
    "B318": tmx_data.layers[30],
    "B319": tmx_data.layers[31],
    "B320": tmx_data.layers[32],
    "B321": tmx_data.layers[33],
    "B322": tmx_data.layers[34],
    "B323": tmx_data.layers[35],
    "B324": tmx_data.layers[36],
    "B325": tmx_data.layers[37],
}
layers_2 = {
    "sol2": tmx_data_b.layers[0],
    "ESCALIER_1": tmx_data_b.layers[1],
    "ESCALIER_2": tmx_data_b.layers[2],
    "ESCALIER_3": tmx_data_b.layers[3],
    "ESCALIER_4": tmx_data_b.layers[4],
    "ESCALIER_5": tmx_data_b.layers[5],
    "ESCALIER_6": tmx_data_b.layers[6],
    "ESCALIER_7": tmx_data_b.layers[7],
    "ESCALIER_8": tmx_data_b.layers[8],
    "COULOIR_F": tmx_data_b.layers[9],
    "COULOIR_G": tmx_data_b.layers[10],
    "COULOIR_H": tmx_data_b.layers[11],
    "COULOIR_I": tmx_data_b.layers[12],
    "COULOIR_J": tmx_data_b.layers[13],
    "COULOIR_K": tmx_data_b.layers[14],
    "COULOIR_L": tmx_data_b.layers[15],
    "COULOIR_M": tmx_data_b.layers[16],
    "murs2": tmx_data_b.layers[17],
    "A201": tmx_data_b.layers[18],
    "A202": tmx_data_b.layers[19],
    "A203": tmx_data_b.layers[20],
    "A204": tmx_data_b.layers[21],
    "A205": tmx_data_b.layers[22],
    "A206": tmx_data_b.layers[23],
    "A207": tmx_data_b.layers[24],
    "A208": tmx_data_b.layers[25],
    "A209": tmx_data_b.layers[26],
    "A210": tmx_data_b.layers[27],
    "A211": tmx_data_b.layers[28],
    "A212": tmx_data_b.layers[29],
    "B213": tmx_data_b.layers[30],
    "B214": tmx_data_b.layers[31],
    "B215": tmx_data_b.layers[32],
    "B216": tmx_data_b.layers[33],
    "B217": tmx_data_b.layers[34],
    "B218": tmx_data_b.layers[35],
    "B219": tmx_data_b.layers[36],
    "B220": tmx_data_b.layers[37],
    "B221": tmx_data_b.layers[38],
    "B222": tmx_data_b.layers[39],
    "B223": tmx_data_b.layers[40],
}
layers_1 = {
    "sol1": tmx_data_b.layers[0],
    "COULOIR_O": tmx_data_d.layers[1],
    "COULOIR_P": tmx_data_d.layers[2],
    "COULOIR_Q": tmx_data_d.layers[3],
    "COULOIR_R": tmx_data_d.layers[4],
    "ESCALIER_6": tmx_data_d.layers[5],
    "ESCALIER_7": tmx_data_d.layers[6],
    "ESCALIER_9": tmx_data_d.layers[7],
    "murs1": tmx_data_d.layers[8],
    "A102": tmx_data_d.layers[9],
    "A103": tmx_data_d.layers[10],
    "A104": tmx_data_d.layers[11],
    "A105": tmx_data_d.layers[12],
    "A106": tmx_data_d.layers[13],
    "A107": tmx_data_d.layers[14],
    "A108": tmx_data_d.layers[15],
}
layers_cdi = {
    "sol_cdi": tmx_data_c.layers[0],
    "COULOIR_S": tmx_data_c.layers[1],
    "COULOIR_T": tmx_data_c.layers[2],
    "COULOIR_U": tmx_data_c.layers[3],
    "COULOIR_V": tmx_data_c.layers[4],
    "COULOIR_W": tmx_data_c.layers[5],
    "COULOIR_X": tmx_data_c.layers[6],
    "ESCALIER_6": tmx_data_c.layers[7],
    "ESCALIER_9": tmx_data_c.layers[8],
    "murs_cdi": tmx_data_c.layers[9],
    "A001": tmx_data_c.layers[10],
    "A002": tmx_data_c.layers[11],
    "A003": tmx_data_c.layers[12],
    "A004": tmx_data_c.layers[13],
    "A005": tmx_data_c.layers[14],
    "A006": tmx_data_c.layers[15],
    "A007": tmx_data_c.layers[16],
    "A008": tmx_data_c.layers[17],
    "A009": tmx_data_c.layers[18],
    "A010": tmx_data_c.layers[19],
    "A011": tmx_data_c.layers[20],
    "A012": tmx_data_c.layers[21],
    "A013": tmx_data_c.layers[22],
    "A014": tmx_data_c.layers[23],
}
layers_1B = {
    "sol": tmx_data_e.layers[0],
    "COULOIR_Y": tmx_data_e.layers[1],
    "COULOIR_Z": tmx_data_e.layers[2],
    "COULOIR_A1": tmx_data_e.layers[3],
    "COULOIR_B1": tmx_data_e.layers[4],
    "COULOIR_C1": tmx_data_e.layers[5],
    "COULOIR_D1": tmx_data_e.layers[6],
    "COULOIR_E1": tmx_data_e.layers[7],
    "ESCALIER_3": tmx_data_e.layers[8],
    "ESCALIER_8": tmx_data_e.layers[9],
    "murs": tmx_data_e.layers[10],
    "B111": tmx_data_e.layers[11],
    "B112": tmx_data_e.layers[12],
    "B113": tmx_data_e.layers[13],
    "B114": tmx_data_e.layers[14],
    "B115": tmx_data_e.layers[15],
    "B116": tmx_data_e.layers[16],
    "B117": tmx_data_e.layers[17],
    "B118": tmx_data_e.layers[18],
}

layers=[layers_2,layers_1,layers_1B,layers_3,layers_cdi]

dico_etage={
    2: layers_1,
    1: layers_cdi,
    3: layers_1B,
    4: layers_2,
    5: layers_3
}
noms_etages={
    1: "CDI",
    2: "B100",
    3: "A100",
    4: "B200-A200",
    5: "A300-B300"
}